name: DAShboard Client CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: yarn install
      working-directory: client
    - uses: hallee/eslint-action@master
      working-directory: client
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Run a build
      run: yarn build
      working-directory: client
