# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - DashMHP

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      # This is to allow github actions to clone our private common repository.
      # The public key is with mhp-deployment github user
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: yarn install, build, and test front-end
        # We use CI='' here because Github Action sets CI=true which makes warnings during
        # install treated like errors
        run: |
          cd client
          CI='' && yarn install
          yarn run build
      
      - name: yarn install, build, and test server
        run: |
          cd server
          CI='' && yarn install

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DashMHP'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: .